# Generated by Django 3.2 on 2021-08-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_published',
            new_name='published',
        ),
    ]
