# Generated by Django 3.2 on 2021-08-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created'], 'verbose_name': 'Equipment Request'},
        ),
        migrations.AddField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
