# Generated by Django 3.2 on 2021-08-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '  Equipment'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-updated'], 'verbose_name': ' Equipments Stock'},
        ),
        migrations.AlterField(
            model_name='request',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.equipment'),
        ),
    ]
