# Generated by Django 3.2 on 2021-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210805_1241'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('user', 'equipment'), name="Can't create multiple stock of same equipment,So update the existing equipment's quantity"),
        ),
    ]
