# Generated by Django 3.2 on 2021-08-05 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', "0005_stock_can't create multiple stock of same equipment,so update the existing equipment's quantity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name="Can't create multiple stock of same equipment,So update the existing equipment's quantity",
        ),
        migrations.AddField(
            model_name='stock',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('user', 'equipment')},
        ),
    ]
