# Generated by Django 3.2 on 2021-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20210806_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('c', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
