# Generated by Django 3.2 on 2021-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_updated',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('d', 'Delivered'), ('c', 'Cancelled')], default='p', max_length=10),
        ),
    ]
