# Generated by Django 3.2 on 2021-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20210807_1117'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name="Can't create multiple stock of same equipment,So update the existing equipment's quantity",
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
